User.create!([
  {
    email: "john.doe@example.com",
    password: "password123",
    password_confirmation: "password123",
    full_name: "John Doe",
    phone: "+507-6123-4567",
    age: 29,
    country: "Panamá",
    city: "Panamá City",
    previous_experience: true,
    previous_courses: true,
    programming_skill_level: "Intermedio",
    motivation: "Me gustaría mejorar mis habilidades de programación para avanzar en mi carrera como desarrollador web.",
    course_expectations: "Espero profundizar mis conocimientos en frameworks como React y mejorar en el desarrollo de aplicaciones web completas.",
    specific_goals: "Crear una aplicación web personalizada para un cliente.",
    has_reliable_computer: true,
    feedback_on_previous_courses: "Los cursos anteriores me dieron una buena base, pero necesito más práctica en proyectos reales.",
    approved: true,
    full_payment_proof: "https://image.slidesharecdn.com/comprobantedepago-141202103655-conversion-gate01/75/Comprobante-de-pago-1-2048.jpg"
  },
  {
    email: "maria.gomez@example.com",
    password: "password123",
    password_confirmation: "password123",
    full_name: "María Gómez",
    phone: "+507-6234-5678",
    age: 25,
    country: "Panamá",
    city: "David",
    previous_experience: false,
    previous_courses: false,
    programming_skill_level: "Principiante",
    motivation: "Estoy interesada en aprender desarrollo web para explorar nuevas oportunidades laborales y emprender proyectos personales.",
    course_expectations: "Quiero adquirir conocimientos sólidos en HTML, CSS y JavaScript para poder construir sitios web desde cero.",
    specific_goals: "Desarrollar un blog personal y entender cómo funciona el hosting y el despliegue web.",
    has_reliable_computer: true,
    feedback_on_previous_courses: "Esta será mi primera experiencia formal en un curso de desarrollo web.",
    approved: true,
    full_payment_proof: "https://image.slidesharecdn.com/comprobantedepago-141202103655-conversion-gate01/75/Comprobante-de-pago-1-2048.jpg"
  },
  {
    email: "juan.lopez@example.com",
    password: "password123",
    password_confirmation: "password123",
    full_name: "Juan López",
    phone: "+507-6345-6789",
    age: 22,
    country: "Panamá",
    city: "Colón",
    previous_experience: false,
    previous_courses: false,
    programming_skill_level: "Novato",
    motivation: "Quiero comenzar una carrera en el campo de la tecnología y creo que aprender programación es el primer paso.",
    course_expectations: "Espero comprender los conceptos básicos de la programación y adquirir habilidades prácticas para resolver problemas.",
    specific_goals: "Participar en proyectos de código abierto y contribuir a la comunidad de desarrollo.",
    has_reliable_computer: true,
    feedback_on_previous_courses: "No tengo experiencia previa en cursos de programación, pero estoy emocionado de comenzar.",
    approved: true,
    full_payment_proof: "https://image.slidesharecdn.com/comprobantedepago-141202103655-conversion-gate01/75/Comprobante-de-pago-1-2048.jpg"
  },
  {
    email: "ana.rodriguez@example.com",
    password: "password123",
    password_confirmation: "password123",
    full_name: "Ana Rodríguez",
    phone: "+507-6456-7890",
    age: 31,
    country: "Panamá",
    city: "Chitré",
    previous_experience: true,
    previous_courses: true,
    programming_skill_level: "Avanzado",
    motivation: "Como desarrolladora experimentada, quiero mantenerme actualizada con las últimas tecnologías y mejorar mis habilidades en desarrollo móvil.",
    course_expectations: "Busco dominar frameworks como Flutter para desarrollar aplicaciones móviles multiplataforma de alta calidad.",
    specific_goals: "Lanzar una aplicación móvil innovadora que resuelva un problema real para los usuarios.",
    has_reliable_computer: true,
    feedback_on_previous_courses: "He tomado varios cursos en el pasado, pero siempre busco expandir mis conocimientos y habilidades.",
    approved: true,
    full_payment_proof: "https://image.slidesharecdn.com/comprobantedepago-141202103655-conversion-gate01/75/Comprobante-de-pago-1-2048.jpg"
  },
  {
    email: "luis.hernandez@example.com",
    password: "password123",
    password_confirmation: "password123",
    full_name: "Luis Hernández",
    phone: "+507-6567-8901",
    age: 27,
    country: "Panamá",
    city: "Santiago",
    previous_experience: true,
    previous_courses: true,
    programming_skill_level: "Intermedio",
    motivation: "Como diseñador gráfico, quiero diversificar mis habilidades y aprender desarrollo web para ofrecer un servicio más completo a mis clientes.",
    course_expectations: "Me gustaría adquirir conocimientos en diseño web responsivo y animaciones para mejorar la experiencia del usuario.",
    specific_goals: "Crear un portfolio en línea para mostrar mi trabajo como diseñador y desarrollador web.",
    has_reliable_computer: true,
    feedback_on_previous_courses: "He realizado algunos cursos en línea, pero necesito más práctica en el desarrollo real de proyectos.",
    approved: true,
    full_payment_proof: "https://image.slidesharecdn.com/comprobantedepago-141202103655-conversion-gate01/75/Comprobante-de-pago-1-2048.jpg"
  },
  {
    email: "carolina.martinez@example.com",
    password: "password123",
    password_confirmation: "password123",
    full_name: "Carolina Martínez",
    phone: "+507-6678-9012",
    age: 24,
    country: "Panamá",
    city: "Los Santos",
    previous_experience: true,
    previous_courses: true,
    programming_skill_level: "Intermedio",
    motivation: "Me apasiona la tecnología y quiero convertir esa pasión en una carrera profesional en desarrollo de software.",
    course_expectations: "Busco mejorar mis habilidades en desarrollo full-stack y aprender a trabajar en equipos ágiles.",
    specific_goals: "Contribuir a proyectos de código abierto y desarrollar una aplicación web innovadora.",
    has_reliable_computer: true,
    feedback_on_previous_courses: "He realizado varios cursos en línea y he trabajado en algunos proyectos, pero siento que aún tengo mucho por aprender.",
    approved: true,
    full_payment_proof: "https://image.slidesharecdn.com/comprobantedepago-141202103655-conversion-gate01/75/Comprobante-de-pago-1-2048.jpg"
  },
  {
    email: "daniel.fernandez@example.com",
    password: "password123",
    password_confirmation: "password123",
    full_name: "Daniel Fernández",
    phone: "+507-6789-0123",
    age: 23,
    country: "Panamá",
    city: "Veraguas",
    previous_experience: true,
    previous_courses: true,
    programming_skill_level: "Intermedio",
    motivation: "Estoy decidido a convertirme en desarrollador de software y trabajar en proyectos desafiantes que tengan un impacto real.",
    course_expectations: "Me gustaría profundizar mis conocimientos en desarrollo backend y aprender a construir API RESTful.",
    specific_goals: "Desarrollar un sistema de gestión de contenido personalizado para un cliente.",
    has_reliable_computer: true,
    feedback_on_previous_courses: "Los cursos que he tomado hasta ahora me han dado una buena base, pero ahora quiero enfocarme en proyectos más avanzados.",
    approved: true,
    full_payment_proof: "https://image.slidesharecdn.com/comprobantedepago-141202103655-conversion-gate01/75/Comprobante-de-pago-1-2048.jpg"
  },
  {
    email: "laura.perez@example.com",
    password: "password123",
    password_confirmation: "password123",
    full_name: "Laura Pérez",
    phone: "+507-6890-1234",
    age: 26,
    country: "Panamá",
    city: "Herrera",
    previous_experience: false,
    previous_courses: false,
    programming_skill_level: "Principiante",
    motivation: "Quiero explorar el campo de la programación y ver si es la carrera adecuada para mí.",
    course_expectations: "Espero aprender los conceptos básicos de la programación y descubrir qué áreas me interesan más.",
    specific_goals: "Crear mi primer proyecto web y ver cómo me siento trabajando en él.",
    has_reliable_computer: true,
    feedback_on_previous_courses: "No tengo experiencia previa en cursos de programación, así que estoy emocionada de comenzar este viaje.",
    approved: true,
    full_payment_proof: "https://image.slidesharecdn.com/comprobantedepago-141202103655-conversion-gate01/75/Comprobante-de-pago-1-2048.jpg"
  }
])
